import type { AppearanceToken } from "./appearanceValue";

export const appearanceTokens: AppearanceToken[] = [
  {
    "id": "palette-bg",
    "cssVar": "--palette-bg",
    "group": "Colours",
    "name": "Window",
    "detail": "Main window background. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#212121",
    "shippedLight": "#ffffff",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-bg-nav",
    "cssVar": "--palette-bg-nav",
    "group": "Colours",
    "name": "Sidebar",
    "detail": "Sidebar background. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#181818",
    "shippedLight": "#f5f5f5",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-bg-panel",
    "cssVar": "--palette-bg-panel",
    "group": "Colours",
    "name": "Panel",
    "detail": "Panels and docks. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#252525",
    "shippedLight": "#fafafa",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-bg-raised",
    "cssVar": "--palette-bg-raised",
    "group": "Colours",
    "name": "Raised",
    "detail": "Cards, menus, and the composer. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#303030",
    "shippedLight": "#ededed",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-bg-input",
    "cssVar": "--palette-bg-input",
    "group": "Colours",
    "name": "Field",
    "detail": "Text fields. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#292929",
    "shippedLight": "#f6f6f6",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-border",
    "cssVar": "--palette-border",
    "group": "Colours",
    "name": "Border",
    "detail": "Borders and dividers. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#3c3c3c",
    "shippedLight": "#dedede",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-text",
    "cssVar": "--palette-text",
    "group": "Colours",
    "name": "Text",
    "detail": "Primary text. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#ececec",
    "shippedLight": "#222222",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-muted",
    "cssVar": "--palette-muted",
    "group": "Colours",
    "name": "Muted",
    "detail": "Secondary text. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#a4a4a4",
    "shippedLight": "#6b6b6b",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-accent",
    "cssVar": "--palette-accent",
    "group": "Colours",
    "name": "Accent",
    "detail": "Accent and selection. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#b5a2ed",
    "shippedLight": "#7250b8",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-warn",
    "cssVar": "--palette-warn",
    "group": "Colours",
    "name": "Warning",
    "detail": "Warnings. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#e4b971",
    "shippedLight": "#90601e",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-danger",
    "cssVar": "--palette-danger",
    "group": "Colours",
    "name": "Danger",
    "detail": "Destructive actions and errors. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#f28d8d",
    "shippedLight": "#bf3e42",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-ok",
    "cssVar": "--palette-ok",
    "group": "Colours",
    "name": "Success",
    "detail": "Success and ready. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#84cba3",
    "shippedLight": "#327950",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-live",
    "cssVar": "--palette-live",
    "group": "Colours",
    "name": "Live",
    "detail": "Activity while a reply is running. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#b5a2ed",
    "shippedLight": "#7250b8",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-hover",
    "cssVar": "--palette-hover",
    "group": "Colours",
    "name": "Hover",
    "detail": "Hover and selected fill. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#343434",
    "shippedLight": "#e8e8e8",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "palette-scrim",
    "cssVar": "--palette-scrim",
    "group": "Colours",
    "name": "Scrim",
    "detail": "Dim layer behind a dialog or viewer. Dark and light are stored separately.",
    "kind": "color",
    "unit": "",
    "shipped": "#0000008c",
    "shippedLight": "#00000066",
    "theme": "split",
    "property": "background-color",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "font-ui",
    "cssVar": "--font-ui",
    "group": "Text",
    "name": "Interface font",
    "detail": "Font used for the application.",
    "kind": "family",
    "unit": "",
    "shipped": "\"Segoe UI Variable\", \"Segoe UI\", sans-serif",
    "shippedLight": null,
    "theme": "all",
    "property": "font-family",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "font-mono",
    "cssVar": "--font-mono",
    "group": "Text",
    "name": "Monospace font",
    "detail": "Code and file paths.",
    "kind": "family",
    "unit": "",
    "shipped": "\"Cascadia Code\", Consolas, monospace",
    "shippedLight": null,
    "theme": "all",
    "property": "font-family",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "text-small",
    "cssVar": "--text-small",
    "group": "Text",
    "name": "Small text",
    "detail": "Hints, badges, eyebrows, and supporting lines.",
    "kind": "length",
    "unit": "px",
    "shipped": "11px",
    "shippedLight": null,
    "theme": "all",
    "property": "font-size",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "text-body",
    "cssVar": "--text-body",
    "group": "Text",
    "name": "Interface text",
    "detail": "Labels, navigation, and most of the application.",
    "kind": "length",
    "unit": "px",
    "shipped": "13px",
    "shippedLight": null,
    "theme": "all",
    "property": "font-size",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "text-ui",
    "cssVar": "--text-ui",
    "group": "Text",
    "name": "Reading text",
    "detail": "Conversation and the composer.",
    "kind": "length",
    "unit": "px",
    "shipped": "14px",
    "shippedLight": null,
    "theme": "all",
    "property": "font-size",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "text-heading",
    "cssVar": "--text-heading",
    "group": "Text",
    "name": "Heading",
    "detail": "Page and section headings.",
    "kind": "length",
    "unit": "px",
    "shipped": "18px",
    "shippedLight": null,
    "theme": "all",
    "property": "font-size",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "text-title",
    "cssVar": "--text-title",
    "group": "Text",
    "name": "Title",
    "detail": "Large titles, such as an empty conversation.",
    "kind": "length",
    "unit": "px",
    "shipped": "24px",
    "shippedLight": null,
    "theme": "all",
    "property": "font-size",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "font-editor",
    "cssVar": "--font-editor",
    "group": "Text",
    "name": "File editor text",
    "detail": "Monaco text size. Interface text and chat code are separate.",
    "kind": "length",
    "unit": "px",
    "shipped": "14px",
    "shippedLight": null,
    "theme": "all",
    "property": "font-size",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "font-code",
    "cssVar": "--font-code",
    "group": "Text",
    "name": "Code text",
    "detail": "Code blocks in the conversation. The file editor is separate.",
    "kind": "length",
    "unit": "px",
    "shipped": "12px",
    "shippedLight": null,
    "theme": "all",
    "property": "font-size",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "weight-regular",
    "cssVar": "--weight-regular",
    "group": "Text",
    "name": "Regular weight",
    "detail": "Body weight.",
    "kind": "number",
    "unit": "",
    "shipped": "400",
    "shippedLight": null,
    "theme": "all",
    "property": "font-weight",
    "allowNegative": false,
    "min": 1,
    "max": 1000,
  },
  {
    "id": "weight-medium",
    "cssVar": "--weight-medium",
    "group": "Text",
    "name": "Medium weight",
    "detail": "Emphasis slightly above body.",
    "kind": "number",
    "unit": "",
    "shipped": "500",
    "shippedLight": null,
    "theme": "all",
    "property": "font-weight",
    "allowNegative": false,
    "min": 1,
    "max": 1000,
  },
  {
    "id": "weight-semibold",
    "cssVar": "--weight-semibold",
    "group": "Text",
    "name": "Semibold",
    "detail": "Headings and primary actions.",
    "kind": "number",
    "unit": "",
    "shipped": "600",
    "shippedLight": null,
    "theme": "all",
    "property": "font-weight",
    "allowNegative": false,
    "min": 1,
    "max": 1000,
  },
  {
    "id": "weight-bold",
    "cssVar": "--weight-bold",
    "group": "Text",
    "name": "Bold",
    "detail": "Strong emphasis.",
    "kind": "number",
    "unit": "",
    "shipped": "700",
    "shippedLight": null,
    "theme": "all",
    "property": "font-weight",
    "allowNegative": false,
    "min": 1,
    "max": 1000,
  },
  {
    "id": "leading-tight",
    "cssVar": "--leading-tight",
    "group": "Text",
    "name": "Tight leading",
    "detail": "Single-line controls and badges.",
    "kind": "number",
    "unit": "",
    "shipped": "1.35",
    "shippedLight": null,
    "theme": "all",
    "property": "line-height",
    "allowNegative": false,
    "min": 0,
    "max": null,
  },
  {
    "id": "leading-body",
    "cssVar": "--leading-body",
    "group": "Text",
    "name": "Body leading",
    "detail": "Conversation and interface text.",
    "kind": "number",
    "unit": "",
    "shipped": "1.5",
    "shippedLight": null,
    "theme": "all",
    "property": "line-height",
    "allowNegative": false,
    "min": 0,
    "max": null,
  },
  {
    "id": "tracking-wide",
    "cssVar": "--tracking-wide",
    "group": "Text",
    "name": "Wide tracking",
    "detail": "Eyebrows and overlines.",
    "kind": "length",
    "unit": "em",
    "shipped": "0.08em",
    "shippedLight": null,
    "theme": "all",
    "property": "letter-spacing",
    "allowNegative": true,
    "min": null,
    "max": null,
  },
  {
    "id": "radius-control",
    "cssVar": "--radius-control",
    "group": "Corners",
    "name": "Control corner",
    "detail": "Buttons, fields, chips, and menus.",
    "kind": "length",
    "unit": "px",
    "shipped": "7px",
    "shippedLight": null,
    "theme": "all",
    "property": "border-radius",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "radius-card",
    "cssVar": "--radius-card",
    "group": "Corners",
    "name": "Card corner",
    "detail": "Cards and panels.",
    "kind": "length",
    "unit": "px",
    "shipped": "12px",
    "shippedLight": null,
    "theme": "all",
    "property": "border-radius",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "radius-composer",
    "cssVar": "--radius-composer",
    "group": "Corners",
    "name": "Composer corner",
    "detail": "The message composer and other large rounded surfaces.",
    "kind": "length",
    "unit": "px",
    "shipped": "21px",
    "shippedLight": null,
    "theme": "all",
    "property": "border-radius",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "radius-pill",
    "cssVar": "--radius-pill",
    "group": "Corners",
    "name": "Pill",
    "detail": "Fully rounded pills.",
    "kind": "length",
    "unit": "px",
    "shipped": "999px",
    "shippedLight": null,
    "theme": "all",
    "property": "border-radius",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "radius-circle",
    "cssVar": "--radius-circle",
    "group": "Corners",
    "name": "Circle",
    "detail": "Circular controls such as send.",
    "kind": "length",
    "unit": "%",
    "shipped": "50%",
    "shippedLight": null,
    "theme": "all",
    "property": "border-radius",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "pad-tight",
    "cssVar": "--pad-tight",
    "group": "Spacing",
    "name": "Tight inset",
    "detail": "Padding inside a button or chip.",
    "kind": "length",
    "unit": "px",
    "shipped": "5px",
    "shippedLight": null,
    "theme": "all",
    "property": "padding",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "pad-compact",
    "cssVar": "--pad-compact",
    "group": "Spacing",
    "name": "Row inset",
    "detail": "Padding inside a row.",
    "kind": "length",
    "unit": "px",
    "shipped": "8px",
    "shippedLight": null,
    "theme": "all",
    "property": "padding",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "pad-card",
    "cssVar": "--pad-card",
    "group": "Spacing",
    "name": "Card inset",
    "detail": "Padding inside cards, popovers, and the composer.",
    "kind": "length",
    "unit": "px",
    "shipped": "14px",
    "shippedLight": null,
    "theme": "all",
    "property": "padding",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "pad-section",
    "cssVar": "--pad-section",
    "group": "Spacing",
    "name": "Section inset",
    "detail": "Padding inside a large section.",
    "kind": "length",
    "unit": "px",
    "shipped": "22px",
    "shippedLight": null,
    "theme": "all",
    "property": "padding",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "pad-page",
    "cssVar": "--pad-page",
    "group": "Spacing",
    "name": "Page inset",
    "detail": "Padding around a page.",
    "kind": "length",
    "unit": "px",
    "shipped": "36px",
    "shippedLight": null,
    "theme": "all",
    "property": "padding",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "space-tight",
    "cssVar": "--space-tight",
    "group": "Spacing",
    "name": "Tight space",
    "detail": "Gap inside a group, such as an icon and its label.",
    "kind": "length",
    "unit": "px",
    "shipped": "4px",
    "shippedLight": null,
    "theme": "all",
    "property": "gap",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "space-compact",
    "cssVar": "--space-compact",
    "group": "Spacing",
    "name": "Item space",
    "detail": "Gap between related items and rows.",
    "kind": "length",
    "unit": "px",
    "shipped": "8px",
    "shippedLight": null,
    "theme": "all",
    "property": "gap",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "space-stack",
    "cssVar": "--space-stack",
    "group": "Spacing",
    "name": "Block space",
    "detail": "Gap between blocks.",
    "kind": "length",
    "unit": "px",
    "shipped": "14px",
    "shippedLight": null,
    "theme": "all",
    "property": "gap",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "space-section",
    "cssVar": "--space-section",
    "group": "Spacing",
    "name": "Section space",
    "detail": "Gap between major regions.",
    "kind": "length",
    "unit": "px",
    "shipped": "24px",
    "shippedLight": null,
    "theme": "all",
    "property": "gap",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "layout-page",
    "cssVar": "--layout-page",
    "group": "Layout",
    "name": "Page width",
    "detail": "Maximum width of a wide page.",
    "kind": "length",
    "unit": "px",
    "shipped": "1500px",
    "shippedLight": null,
    "theme": "all",
    "property": "max-width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "layout-reading",
    "cssVar": "--layout-reading",
    "group": "Layout",
    "name": "Reading width",
    "detail": "Maximum width of the composer and other reading columns.",
    "kind": "length",
    "unit": "px",
    "shipped": "860px",
    "shippedLight": null,
    "theme": "all",
    "property": "max-width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "layout-message",
    "cssVar": "--layout-message",
    "group": "Layout",
    "name": "Message width",
    "detail": "How wide a person's own message can grow.",
    "kind": "length",
    "unit": "%",
    "shipped": "78%",
    "shippedLight": null,
    "theme": "all",
    "property": "max-width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "layout-panel",
    "cssVar": "--layout-panel",
    "group": "Layout",
    "name": "Panel width",
    "detail": "Width of a medium panel or form.",
    "kind": "length",
    "unit": "px",
    "shipped": "520px",
    "shippedLight": null,
    "theme": "all",
    "property": "max-width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "layout-dialog",
    "cssVar": "--layout-dialog",
    "group": "Layout",
    "name": "Dialog width",
    "detail": "Width of a dialog or small popover.",
    "kind": "length",
    "unit": "px",
    "shipped": "360px",
    "shippedLight": null,
    "theme": "all",
    "property": "max-width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "layout-side",
    "cssVar": "--layout-side",
    "group": "Layout",
    "name": "Side column",
    "detail": "Width of a library or side list.",
    "kind": "length",
    "unit": "px",
    "shipped": "200px",
    "shippedLight": null,
    "theme": "all",
    "property": "width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "layout-column",
    "cssVar": "--layout-column",
    "group": "Layout",
    "name": "Wide column",
    "detail": "Width of a popover or the file preview.",
    "kind": "length",
    "unit": "px",
    "shipped": "250px",
    "shippedLight": null,
    "theme": "all",
    "property": "width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "layout-narrow",
    "cssVar": "--layout-narrow",
    "group": "Layout",
    "name": "Narrow width",
    "detail": "Short widths, such as a date column.",
    "kind": "length",
    "unit": "px",
    "shipped": "90px",
    "shippedLight": null,
    "theme": "all",
    "property": "width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "layout-inset",
    "cssVar": "--layout-inset",
    "group": "Layout",
    "name": "Content inset",
    "detail": "Side inset of a centered column.",
    "kind": "length",
    "unit": "px",
    "shipped": "42px",
    "shippedLight": null,
    "theme": "all",
    "property": "width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "layout-menu",
    "cssVar": "--layout-menu",
    "group": "Layout",
    "name": "Tall panel height",
    "detail": "Maximum height of a menu, a diff, or an open reasoning panel.",
    "kind": "length",
    "unit": "px",
    "shipped": "420px",
    "shippedLight": null,
    "theme": "all",
    "property": "max-height",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "layout-control",
    "cssVar": "--layout-control",
    "group": "Layout",
    "name": "Control column",
    "detail": "Width of the control column in setting rows, so every switch, slider and field lines up.",
    "kind": "length",
    "unit": "px",
    "shipped": "300px",
    "shippedLight": null,
    "theme": "all",
    "property": "width",
    "allowNegative": false,
    "min": 160,
    "max": 600,
  },
  {
    "id": "layout-form",
    "cssVar": "--layout-form",
    "group": "Layout",
    "name": "Form width",
    "detail": "Maximum width of settings pages, forms and record editors.",
    "kind": "length",
    "unit": "px",
    "shipped": "780px",
    "shippedLight": null,
    "theme": "all",
    "property": "max-width",
    "allowNegative": false,
    "min": 480,
    "max": 1400,
  },
  {
    "id": "control-height",
    "cssVar": "--control-height",
    "group": "Layout",
    "name": "Control height",
    "detail": "Minimum height of buttons and fields.",
    "kind": "length",
    "unit": "px",
    "shipped": "30px",
    "shippedLight": null,
    "theme": "all",
    "property": "min-height",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "control-height-lg",
    "cssVar": "--control-height-lg",
    "group": "Layout",
    "name": "Large control height",
    "detail": "Taller buttons and tiles.",
    "kind": "length",
    "unit": "px",
    "shipped": "38px",
    "shippedLight": null,
    "theme": "all",
    "property": "min-height",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "icon-md",
    "cssVar": "--icon-md",
    "group": "Layout",
    "name": "Small icon",
    "detail": "Checkboxes and small icons.",
    "kind": "length",
    "unit": "px",
    "shipped": "16px",
    "shippedLight": null,
    "theme": "all",
    "property": "width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "icon-lg",
    "cssVar": "--icon-lg",
    "group": "Layout",
    "name": "Large icon",
    "detail": "Larger icons, such as help.",
    "kind": "length",
    "unit": "px",
    "shipped": "20px",
    "shippedLight": null,
    "theme": "all",
    "property": "width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "icon-xl",
    "cssVar": "--icon-xl",
    "group": "Layout",
    "name": "Extra large icon",
    "detail": "The largest icons.",
    "kind": "length",
    "unit": "px",
    "shipped": "28px",
    "shippedLight": null,
    "theme": "all",
    "property": "width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "line-hairline",
    "cssVar": "--line-hairline",
    "group": "Lines",
    "name": "Hairline",
    "detail": "Standard 1px borders and dividers.",
    "kind": "length",
    "unit": "px",
    "shipped": "1px",
    "shippedLight": null,
    "theme": "all",
    "property": "border-width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "line-strong",
    "cssVar": "--line-strong",
    "group": "Lines",
    "name": "Strong line",
    "detail": "Selected tabs, focus, and emphasis.",
    "kind": "length",
    "unit": "px",
    "shipped": "2px",
    "shippedLight": null,
    "theme": "all",
    "property": "border-width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "focus-ring",
    "cssVar": "--focus-ring",
    "group": "Lines",
    "name": "Focus ring",
    "detail": "Thickness of the keyboard focus ring.",
    "kind": "length",
    "unit": "px",
    "shipped": "2px",
    "shippedLight": null,
    "theme": "all",
    "property": "outline-width",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "focus-offset",
    "cssVar": "--focus-offset",
    "group": "Lines",
    "name": "Focus offset",
    "detail": "Space between a control and its focus ring.",
    "kind": "length",
    "unit": "px",
    "shipped": "2px",
    "shippedLight": null,
    "theme": "all",
    "property": "outline-offset",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "icon-stroke",
    "cssVar": "--icon-stroke",
    "group": "Lines",
    "name": "Icon stroke",
    "detail": "Line thickness of icons.",
    "kind": "number",
    "unit": "",
    "shipped": "1.7",
    "shippedLight": null,
    "theme": "all",
    "property": "stroke-width",
    "allowNegative": false,
    "min": 0,
    "max": null,
  },
  {
    "id": "palette-shadow",
    "cssVar": "--palette-shadow",
    "group": "Effects",
    "name": "Shadow",
    "detail": "Menus and popovers. Dark and light are stored separately.",
    "kind": "shadow",
    "unit": "",
    "shipped": "0 12px 40px #0005",
    "shippedLight": "0 12px 40px #0000001a",
    "theme": "split",
    "property": "box-shadow",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "shadow-soft",
    "cssVar": "--shadow-soft",
    "group": "Effects",
    "name": "Soft shadow",
    "detail": "Cards and the composer. Dark and light are stored separately.",
    "kind": "shadow",
    "unit": "",
    "shipped": "0 8px 28px #0008",
    "shippedLight": "0 4px 20px #0000001a",
    "theme": "split",
    "property": "box-shadow",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
  {
    "id": "fade-disabled",
    "cssVar": "--fade-disabled",
    "group": "Effects",
    "name": "Disabled fade",
    "detail": "Opacity of disabled controls.",
    "kind": "number",
    "unit": "",
    "shipped": "0.45",
    "shippedLight": null,
    "theme": "all",
    "property": "opacity",
    "allowNegative": false,
    "min": 0,
    "max": 1,
  },
  {
    "id": "fade-quiet",
    "cssVar": "--fade-quiet",
    "group": "Effects",
    "name": "Quiet fade",
    "detail": "Opacity of secondary or de-emphasised content.",
    "kind": "number",
    "unit": "",
    "shipped": "0.7",
    "shippedLight": null,
    "theme": "all",
    "property": "opacity",
    "allowNegative": false,
    "min": 0,
    "max": 1,
  },
  {
    "id": "tint-quiet",
    "cssVar": "--tint-quiet",
    "group": "Effects",
    "name": "Quiet tint",
    "detail": "A light colour mix, such as a faint wash.",
    "kind": "length",
    "unit": "%",
    "shipped": "16%",
    "shippedLight": null,
    "theme": "all",
    "property": "opacity",
    "allowNegative": false,
    "min": 0,
    "max": 100,
  },
  {
    "id": "tint-soft",
    "cssVar": "--tint-soft",
    "group": "Effects",
    "name": "Soft tint",
    "detail": "A modest colour mix, such as selection.",
    "kind": "length",
    "unit": "%",
    "shipped": "35%",
    "shippedLight": null,
    "theme": "all",
    "property": "opacity",
    "allowNegative": false,
    "min": 0,
    "max": 100,
  },
  {
    "id": "tint-half",
    "cssVar": "--tint-half",
    "group": "Effects",
    "name": "Half tint",
    "detail": "A roughly even colour mix.",
    "kind": "length",
    "unit": "%",
    "shipped": "50%",
    "shippedLight": null,
    "theme": "all",
    "property": "opacity",
    "allowNegative": false,
    "min": 0,
    "max": 100,
  },
  {
    "id": "tint-strong",
    "cssVar": "--tint-strong",
    "group": "Effects",
    "name": "Strong tint",
    "detail": "A heavy colour mix.",
    "kind": "length",
    "unit": "%",
    "shipped": "78%",
    "shippedLight": null,
    "theme": "all",
    "property": "opacity",
    "allowNegative": false,
    "min": 0,
    "max": 100,
  },
  {
    "id": "effect-blur",
    "cssVar": "--effect-blur",
    "group": "Effects",
    "name": "Dialog blur",
    "detail": "Blur behind a dialog.",
    "kind": "length",
    "unit": "px",
    "shipped": "3px",
    "shippedLight": null,
    "theme": "all",
    "property": "backdrop-filter",
    "allowNegative": false,
    "min": null,
    "max": null,
  },
];
