import { Help, tokenLabel } from "./ModelControls";
import { labDepths, labIsActive, labStatus } from "./labPresentation";
import type { LabMeasurement, LabRun } from "./labTypes";

export const labDate = (date: string) => new Date(date).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
const number = (value: number | null | undefined, speed = false) => typeof value === "number" ? speed ? value.toLocaleString(undefined, { maximumFractionDigits: 1 }) : value.toLocaleString() : "—";

export function LabRunStatus({ run, onStop, busy }: { run: LabRun; onStop: (run: LabRun) => void; busy: boolean }) {
  const current = run.current;
  const depth = labDepths.find(item => item.value === current?.depth)?.label;
  const detail = run.error ?? (typeof current?.message === "string" ? current.message : depth ? `${depth} depth` : typeof current?.prompt_length === "number" ? `${tokenLabel(current.prompt_length)} prompt` : null);
  return <div className={`lab-run-status${run.status === "failed" ? " lab-run-failed" : ""}`} role="status"><div><strong>{labStatus(run)}{detail ? ` · ${detail}` : ""}</strong><span className="hint">{run.status === "stopped" ? "Finished measurements are saved. Remaining measurements were skipped." : `${run.measurements.filter(item => !item.error).length} finished · ${run.series.map(item => item.name).join(", ") || "Preparing configuration"}`}</span></div>{labIsActive(run) ? <button type="button" disabled={busy || run.status === "stopping"} onClick={() => onStop(run)}>{run.status === "stopping" ? "Stopping…" : "Stop"}</button> : null}</div>;
}

export function PerformanceResults({ runs, hidden, onToggle, onDelete }: { runs: LabRun[]; hidden: ReadonlySet<string>; onToggle: (id: string) => void; onDelete: (run: LabRun) => void }) {
  if (!runs.length) return <div className="empty-state"><h3>No benchmarks yet</h3><p>Choose a model and at least one prompt length, then run a benchmark.</p></div>;
  return <section className="card lab-saved-runs"><h3>Saved benchmarks</h3>{runs.map(run => <article className="lab-saved-run" key={run.id}><div className="section-heading"><label className="check-row"><input type="checkbox" checked={!hidden.has(run.id)} aria-label={`Show benchmark ${labDate(run.created_at)}`} onChange={() => onToggle(run.id)} /><span>{run.series.map(series => series.name).join(" + ") || "Preparing benchmark"}</span></label><button type="button" className="text-button" disabled={labIsActive(run)} aria-label={`Delete benchmark ${labDate(run.created_at)}`} onClick={() => onDelete(run)}>Delete</button></div><p className="hint">{labDate(run.created_at)} · {run.request.mode === "single" ? "Single stream" : "Concurrent serving"} · {labStatus(run)} · {run.request.generation_length} output tokens</p>{run.error ? <p className="lab-error">{run.error}</p> : null}
    {run.series.filter(series => series.context_adjusted).map(series => <p className="hint" key={series.id}>{series.name}: loaded context per request is {number(series.context_size)} tokens; requested total was {number(series.requested_context_size)}. Memory fitting or shared request capacity changed the available context.</p>)}
    <details><summary>Measurements and settings</summary><div className="lab-table-scroll"><table className="lab-measurements"><caption className="sr-only">Finished measurements from the loaded model</caption><thead><tr><th>Configuration</th><th>Requested prompt</th><th>Reported prompt</th><th>Reported context</th><th>Output</th><th>Prefill t/s</th><th>Generation t/s</th></tr></thead><tbody>{run.measurements.map(point => <tr key={point.id}><td>{run.series.find(series => series.id === point.series_id)?.name ?? "Configuration"}</td><td>{number(point.requested_prompt_length)}</td>{point.error ? <td colSpan={5} className="lab-error">{point.error}</td> : <><td>{number(point.prompt_tokens)}</td><td>{number(point.context_tokens)}</td><td>{number(point.generated_tokens)}</td><td>{number(point.prefill_tps, true)}</td><td>{number(point.generation_tps, true)}</td></>}</tr>)}</tbody></table></div><p className="hint">Reported lengths include the model's actual measurement. Room is reserved for generation.</p>
    {run.series.map(series => <details className="lab-series-settings" key={series.id}><summary>{series.name} · {series.concurrent_requests} {series.concurrent_requests === 1 ? "request" : "concurrent requests"}</summary><dl className="lab-settings-list"><div><dt>Loaded context</dt><dd>{number(series.context_size)} tokens</dd></div>{Object.entries(series.startup).map(([key, value]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{typeof value === "object" ? JSON.stringify(value) : String(value)}</dd></div>)}</dl></details>)}
    {run.measurements.some(point => point.samples.length > 1) ? <details><summary>Individual concurrent requests <Help label="Concurrent measurements">Charts show the reported mean speed for a configuration while its requests run together. Individual server measurements are retained here.</Help></summary><pre>{JSON.stringify(run.measurements.filter(point => point.samples.length > 1).map(point => ({ requested_prompt: point.requested_prompt_length, samples: point.samples })), null, 2)}</pre></details> : null}</details></article>)}</section>;
}

export function MemoryResults({ runs, onDelete }: { runs: LabRun[]; onDelete: (run: LabRun) => void }) {
  if (!runs.length) return <div className="empty-state"><h3>No memory tests yet</h3><p>Choose a model, a needle test and the depths to check.</p></div>;
  return <div className="lab-memory-runs">{runs.map((run, index) => <details className="card lab-memory-run" key={run.id} open={index === 0 || labIsActive(run)}><summary><span>{({ uuid: "Single UUID", multi_key: "Multi-key", multi_value: "Multi-value" })[run.request.memory_test]} · {run.series[0]?.name ?? "Preparing model"}</span><span className="hint">{labStatus(run)}</span></summary><div className="section-heading"><p className="hint">{labDate(run.created_at)} · {number(run.series[0]?.context_size)} context tokens</p><button type="button" className="text-button" disabled={labIsActive(run)} onClick={() => onDelete(run)}>Delete run</button></div>{run.error ? <p className="lab-error">{run.error}</p> : null}{labDepths.filter(depth => run.request.depths.includes(depth.value)).map(depth => {
    const point = run.measurements.find(item => item.depth === depth.value);
    const current = labIsActive(run) && run.current?.depth === depth.value;
    return <details className="lab-depth-result" key={depth.value}><summary><span>{depth.label}</span>{point?.error ? <span className="lab-error">Failed</span> : point ? <span className={`badge ${point.found ? "tone-ok" : "tone-warn"}`}>{point.found ? "Found" : "Missed"}{point.missing.length ? ` · ${point.missing.length} ${point.missing.length === 1 ? "value" : "values"} absent` : ""}</span> : <span className="hint">{current ? "Running…" : "Not run"}</span>}</summary>{point ? <><LabAnswer point={point} />{point.missing.length ? <div className="lab-missing"><span className="hint">Missing values</span>{point.missing.map(value => <code key={value}>{value}</code>)}</div> : null}<p className="hint">Reported prompt {number(point.prompt_tokens)} · context {number(point.context_tokens)} tokens</p></> : <p className="hint">No result recorded for this depth.</p>}</details>;
  })}</details>)}</div>;
}

export function LabAnswer({ point }: { point: LabMeasurement }) {
  return <>{point.error ? <p className="lab-error">{point.error}</p> : null}<pre className="lab-answer">{point.answer || "No answer text returned."}</pre></>;
}
